### ISSUE TITLE
How is this different from using custom user fields?

### ISSUE THREAD

**Issue by mudrd8mz** [cbluesprl/moodle-local_custom_registration#1]
https://docs.moodle.org/en/User_profile_fields - allows admins to define custom fields together with their display at the signup form. Does this plugin aim at the same / similar functionality? What are the benefits of it?

**Comment by mudrd8mz** [comment]
Right. I understand it like a way to make use of the standard profile fields and force them provided during the sign up. Without the need to re-define the same fields as custom ones. It makes sense.

**Comment by MallauryGerard** [comment]
Hello,

Yes, that is exactly it. Also, it avoids duplicates in the database and confusion between "regular" and "custom" user fields
